language: java
jdk:
- oraclejdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "ThPgZ24p1P6e48240sibn7cMRTW/iJlgXdoZMB/9geQcBAb5zENbG4GPxf4+DXSW5guuhYldXYR+Le0nbxt10zUYPYda9WXpZX81y2O0Zghi2dc0HcxcB7GS0kW2XJxg0k9pMFI88arRy0mtzgOuWCjecl5QMYRjY818rPlPIml37CtXPq9JwSMLsx8UHmFnQw+wtBk9JYZNOvYoqx8NIWe8ocGP3Yvn9HFfDvvAX6ORI691BP5HrnC01aGcC9GiFedj173ADurorjCkqk3X4kSvmZlHqeN9zfnqkjM2Gvj8iMofV4cVHEV8vT089r/o0Y/cf81tnCVv2HDXoLivWn+yAgLI2X7ZXSgVaI/wqk0mOztW131Rgb2/OwczCIG7p6GQlMyibq/aozUITTl7xYfApQS/3G9HwsQx1UBWt1D7qenozHnpbO2P1SpCrVwCuO9XnjFqUT6jaYuYADlNqKRv1RcJmaCRc2kBe4o08gLZXZFn8WZxkiS7Y28hbxV1n7zQIil+DZAv9DYog6iQZEtg5FyZOcYwzSlCsKwTVvJrCJ7K7ysbBuBoY3xIi66HnmJsnuZxRxO6fCWoindeT8EzDTySGiirxG1yLHI+KJmsHjEWCAfcW9hNLsLIobKnHPuPth6DrF4MhkalrpLMTIbwnrJm6j4oD34Jy9nPAmE="
  - secure: "Ea8UKdDJUEM7KZ58yTEltx5nYOXJ3g+wtSeA3opSOoxQRYvxoYK6zAEEDo3slphFkCk58xHE9DOmcsEE5c12g4m72WVnAHXiPTmgkS7xun0gTTZL9fjY+LtFVelkHzEJ0qzv4ra2x26bYdHGC2GNkrJY7JNcfNDW8kdn6w7V7OUceWKJd2Jrju9oxGACuCLtmKHVvQdMcEVG/F6VfGnKvIVWuBUIvNs+Y39UfmvRrfv9pvk3I7eY5+0vgB0XZBLd7WbcrRsYTZUwkWN9lrl/CdNNQjCH0Hh1flQ9RX4lr8lBG6/JPtHLnat8k2mE9+YqAcF3NuUANJvO9v+2V7CZrMfO0nUj2k2cNd1SNqujVwGB/Zv5IWQwtETQNcppbMOuxjYAeafCe5Dn+fRo1V2lQ1knwxVbF4VzccIqFEUGB523Il7AN0KblxXjoHxza2NxJ57Syzwjg0/+XHMlyw+0g0dFdpPw6QZwHLrozCaAY1Z1R3Jq8d4bxxvZ+A2f6SEEVHqHj79TkVQym6Rah4OXKC0wHrCowB91HG6+9yhrVWJCX+BJuXewT01B88ZM6efT3ZG9NEjfZ+UKjnmtbvynLmTMe9Ej+xt6egwF3XHbnSQSsWB2VMoDXv2j3HLMY323QSoOFi6evFqp0Dxgo59U7MV9pUajB5ui9ltoD94Tvoc="
deploy:
  provider: releases
  api_key: 
    secure: "jlwGuR4sKR4pBSCoSvEaIzUbrhs8sQo98qf2RWGULcevvdYa5UoQ5/aA/iOEsCQX9ZXATqeM8zpxXTxJzHULPnTVCOFgRN4hKHADciQ/yh8iTBPwTZELEi545meMvQYqz1kxkV5mXKiINyTH4CAVg2DLQvXe5pZGt0+8J8I2g7WVug57c1GB5qHFEidSq1I4T8Vq1pFfbxdnRZOY9lqAjL54tskwISlotOkhpczoNNPHbc3xTjikqZtvPh/FHCy6nNJg3nZ3OeGGZQVtcIXIQ/CFVRjODFjAysvMA5tSnE9llCF8MYjrwodpLcJI+nxUwau7VM9iVel55TU0ovUHlFoKrLEwfJMKULzU3oGRDlTXK1qlXhZA+IYfEa7Jpnk5T5jda7ajwwu321ud69/ZTLVSpbK21Pn/FJb7MTV1Ekg9vIO6rIqCBf446GfrpPl8qECqkuOsIPM/L5s3deKr07VNMKZ1fiQMF94Fb7HehP9r8bOEoMRS4Zj4jn7jnNUq4rCRjXAdIr5N9pqOjvILeQtgxp85pvkgpdtGEn9rz8/eEdv7iDMLueCs3Hq4Yi7uW9s3z2/AdTz4SHpw58E/mndYKh8DXDF8qj/B2gelFR5kUVtOgwdqTU2/5cGIWkW1mu8R6YVZ9wp6T5uSw7/T/vEkXZJR1Qpgg3LZmLKw4TY="
  file_glob: true
  file: 
    - "target/AnimatedFrames_v*.jar"
  skip_cleanup: true
  on:
    tags: true
